# Generated by Django 5.2.5 on 2025-09-22 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_chat_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
