# Generated by Django 5.2.5 on 2025-11-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_name', models.CharField(unique=True)),
                ('sender_id', models.CharField()),
                ('receiver_id', models.CharField()),
            ],
        ),
    ]
