# Generated by Django 5.2.5 on 2025-11-30 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_chatroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='ch_name',
            new_name='ch_room_name',
        ),
    ]
