# Generated by Django 5.2.5 on 2025-11-30 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_ch_name_chatroom_ch_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='receiver_id',
            new_name='receiver_name',
        ),
        migrations.RenameField(
            model_name='chatroom',
            old_name='sender_id',
            new_name='sender_name',
        ),
    ]
