# Generated by Django 5.2.5 on 2025-11-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_receiver_id_chatroom_receiver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='first_name',
            field=models.TextField(null=True),
        ),
    ]
