# Generated by Django 5.2.5 on 2025-11-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_chatroom_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='first_name',
            field=models.TextField(),
        ),
    ]
