# Generated by Django 5.2.5 on 2025-12-02 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user_id',
            new_name='user',
        ),
    ]
